{% set name = "MaBoSS" %}
{% set version = "2.3.4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../..

build:
  number: 0
  binary_relocation: False

requirements:
  build:
    - {{ compiler('cxx') }}
    - flex
    - bison
    - make

about:
  home:  https://maboss.curie.fr

