name: Conda packages for MaBoSS

on:
  workflow_run:
    workflows: ["MaBoSS Tests"]
    branches: [master]
    types: 
      - completed

jobs:
  maboss_conda_defaults:
    name: Build MaBoSS Anaconda package
    runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda update conda --all
        conda install conda-build anaconda-client conda-verify
      
    - name: Build Anaconda package
      run: |
        conda build -c colomoto conda/maboss

    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-defaults-${{ github.run_id }}
           
  maboss_conda:
    name: Build MaBoSS Anaconda package (conda-forge)
    runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda --all
        conda install conda-build anaconda-client conda-verify
      
    - name: Build Anaconda package
      run: |
        CUSTOM_BUILD_NUMBER=1 conda build -c colomoto conda/maboss

    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
        
  
  maboss_conda_test_defaults:
    name: Test MaBoSS Anaconda package
    runs-on: ubuntu-20.04
    needs: maboss_conda_defaults
     
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-defaults-${{ github.run_id }}
        
    - name: Install conda-build
      run: |
        conda update conda
        conda update conda --all
        conda install conda-build
     
    - name: Install package
      run: |
        conda index /usr/share/miniconda/conda-bld
        conda install --use-local -c colomoto maboss
       
    - name: Test package
      run: |
        pip install numpy
        export MABOSS=/usr/share/miniconda/bin/MaBoSS
        export MABOSS_128n=/usr/share/miniconda/bin/MaBoSS_128n
        export MABOSS_CLIENT=/usr/share/miniconda/bin/MaBoSS-client
        export MABOSS_SERVER=/usr/share/miniconda/bin/MaBoSS-server
        export MABOSS_SERVER_128n=/usr/share/miniconda/bin/MaBoSS_128n-server
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
  maboss_conda_test:
    name: Test MaBoSS Anaconda package (conda-forge)
    runs-on: ubuntu-20.04
    needs: maboss_conda
     
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
        
    - name: Install conda-build
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda --all
        conda install conda-build
     
    - name: Install package
      run: |
        conda index /usr/share/miniconda/conda-bld
        conda install --use-local -c colomoto maboss
       
    - name: Test package
      run: |
        pip install numpy
        export MABOSS=/usr/share/miniconda/bin/MaBoSS
        export MABOSS_128n=/usr/share/miniconda/bin/MaBoSS_128n
        export MABOSS_CLIENT=/usr/share/miniconda/bin/MaBoSS-client
        export MABOSS_SERVER=/usr/share/miniconda/bin/MaBoSS-server
        export MABOSS_SERVER_128n=/usr/share/miniconda/bin/MaBoSS_128n-server
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
        
  maboss_conda_publish_defaults:
    name: Publish MaBoSS Anaconda package
    runs-on: ubuntu-20.04
    needs: maboss_conda_test_defaults
     
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Restoring cached conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-defaults-${{ github.run_id }}
    
    - name: Install anaconda-client
      run: |
        conda update conda
        conda update --all
        conda install anaconda-client
    
    - name: Upload MaBoSS Ananconda package on vincent-noel
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0' && github.ref == 'refs/heads/master'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --force;
    
    - name: Upload MaBoSS Ananconda package on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS-env-2.0' && github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --force;
    
  maboss_conda_publish:
    name: Publish MaBoSS Anaconda package (conda-forge)
    runs-on: ubuntu-20.04
    needs: maboss_conda_test
     
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Restoring cached conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/share/miniconda/conda-bld/linux-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
    
    - name: Install anaconda-client
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update --all
        conda install anaconda-client
    
    - name: Upload MaBoSS Ananconda package on vincent-noel
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0' && github.ref == 'refs/heads/master'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --force;
    
    - name: Upload MaBoSS Ananconda package on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS-env-2.0' && github.event_name == 'release'
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --force;
    
  
  
      
  conda_maboss_macosx:
    name: Build Conda MaBoSS package
    runs-on: macos-11
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'

    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Installing conda-build      
      run: |
        conda update conda
        conda update conda --all
        conda install conda-build conda-verify
    - name: Downgrading XCode to 11.7
      run: |
        sudo xcode-select -s /Applications/Xcode_11.7.app/Contents/Developer
        brew reinstall llvm    
    - name: Build MaBoSS Anaconda package
      run: |
        conda build -c colomoto conda/maboss
          
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
        
  conda_maboss_conda_forge_macosx:
    name: Build Conda MaBoSS package (conda-forge)
    runs-on: macos-11
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'

    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1

    - name: Installing conda-build      
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda --all
        conda install conda-build conda-verify
    - name: Build MaBoSS Anaconda package
      run: |
        CUSTOM_BUILD_NUMBER=1 conda build -c colomoto conda/maboss
          
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-forge-${{ github.run_id }}
   
  maboss_conda_test_macosx:
    name: MaBoSS Anaconda package test
    runs-on: macos-11
    needs: conda_maboss_macosx
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda update conda --all
        conda install conda-build anaconda-client
      
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
        
    - name: Install package
      run: |
        conda index /usr/local/miniconda/conda-bld
        conda install -c colomoto maboss --use-local
      
    - name: Test package
      run: |
        pip install numpy
        export MABOSS=/usr/local/miniconda/bin/MaBoSS
        export MABOSS_128n=/usr/local/miniconda/bin/MaBoSS_128n
        export MABOSS_CLIENT=/usr/local/miniconda/bin/MaBoSS-client
        export MABOSS_SERVER=/usr/local/miniconda/bin/MaBoSS-server
        export MABOSS_SERVER_128n=/usr/local/miniconda/bin/MaBoSS_128n-server
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
  
  maboss_conda_test_conda_forge_macosx:
    name: MaBoSS Anaconda package test (conda-forge)
    runs-on: macos-11
    needs: conda_maboss_conda_forge_macosx
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda --all
        conda install conda-build anaconda-client
      
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-forge-${{ github.run_id }}
        
    - name: Install package
      run: |
        conda index /usr/local/miniconda/conda-bld
        conda install -c colomoto maboss --use-local
      
    - name: Test package
      run: |
        pip install numpy
        export MABOSS=/usr/local/miniconda/bin/MaBoSS
        export MABOSS_128n=/usr/local/miniconda/bin/MaBoSS_128n
        export MABOSS_CLIENT=/usr/local/miniconda/bin/MaBoSS-client
        export MABOSS_SERVER=/usr/local/miniconda/bin/MaBoSS-server
        export MABOSS_SERVER_128n=/usr/local/miniconda/bin/MaBoSS_128n-server
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-server.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"
        bash -c "cd engine/tests; bash ./test-rngs.sh"
        bash -c "cd engine/tests; bash ./test-sbml.sh"
    
  maboss_conda_publish_macosx:
    name: MaBoSS Anaconda package publication
    runs-on: macos-11
    needs: maboss_conda_test_macosx
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda update conda --all
        conda install conda-build anaconda-client
      
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-${{ github.run_id }}
        
    
    - name: Upload MaBoSS to Anaconda cloud on vincent-noel
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0' && github.ref == 'refs/heads/master'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 
    
    - name: Upload MaBoSS to Anaconda cloud on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS-env-2.0' && github.event_name == 'release'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 
  maboss_conda_publish_conda_forge_macosx:
    name: MaBoSS Anaconda package publication (conda-forge)
    runs-on: macos-11
    needs: maboss_conda_test_conda_forge_macosx
    
    steps:
    - uses: actions/checkout@v3
    - uses: s-weigand/setup-conda@v1
    
    - name: Install conda-build
      run: |
        conda update conda
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        conda update conda --all
        conda install conda-build anaconda-client
      
    - name: Caching produced conda package
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/miniconda/conda-bld/osx-64/*
        key: ${{ runner.os }}-maboss-conda-forge-${{ github.run_id }}
        
    
    - name: Upload MaBoSS to Anaconda cloud on vincent-noel
      if: github.repository == 'vincent-noel/MaBoSS-env-2.0' && github.ref == 'refs/heads/master'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u vincent-noel /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 
    
    - name: Upload MaBoSS to Anaconda cloud on colomoto
      if: github.repository == 'sysbio-curie/MaBoSS-env-2.0' && github.event_name == 'release'
      run: |   
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u colomoto /usr/local/miniconda/conda-bld/osx-64/*.tar.bz2 --force;
 