name: Build and deploy containers

on: 
  workflow_run:
    workflows: ["MaBoSS Tests"]
    branches: [master]
    types: 
      - completed

jobs:
  test_docker:
    name: Docker MaBoSS Server
    runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get install flex bison
        pip install numpy
      
    - name: Start MaBoSS docker server
      run: |
        docker-compose up -d maboss-server
        bash -c "cd engine/src; make client"
        
    - name: Test MaBoSS docker server
      run: |
        bash -c "cd engine/tests; bash ./test-container.sh"
  
    - name: Connect Docker Hub
      if: github.event_name == 'release' && github.event.action == 'created' && github.repository == 'sysbio-curie/MaBoSS-env-2.0'
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
    - name: Upload Docker Hub
      if: github.event_name == 'release' && github.event.action == 'created' && github.repository == 'sysbio-curie/MaBoSS-env-2.0'
      run: | 
          docker tag maboss-server:latest vnoel/maboss-server:latest
          docker push vnoel/maboss-server:latest
    
  test_singularity:
    name: Singularity MaBoSS Server
    runs-on: ubuntu-20.04
    # if: github.ref == 'refs/heads/master' || github.event_name == 'release'
   
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        wget -O- http://neuro.debian.net/lists/bionic.de-m.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
        sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com 0xA5D32F012649A5A9
        sudo apt-get -qq update
        sudo apt-get install -yq singularity-container debootstrap
        sudo apt-get install flex bison
        pip install numpy
      
    - name: Start MaBoSS Singularity server
      run: |
        sudo singularity build maboss-server.simg containers/singularity/Singularity
        singularity run maboss-server.simg &
        bash -c "cd engine/src; make client"
        
    - name: Test MaBoSS
      run: |
        bash -c "cd engine/tests; bash ./test-container.sh"
    