name: Tests Windows

on:
  push:
  pull_request:
    
jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: flex bison make gcc diffutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-python-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-lapack mingw-w64-x86_64-openblas
        
    - name: Build MaBoSS
      run: |
        cd engine/src
        make MAXNODES=128 maboss
        make maboss

    - name: Test MaBoSS
      run: |
        bash -c "cd engine/tests; bash ./test-cellcycle.sh"
        bash -c "cd engine/tests; bash ./test-ensemble.sh"
        bash -c "cd engine/tests; bash ./test-ewing.sh"
        bash -c "cd engine/tests; bash ./test-user_func.sh"
        bash -c "cd engine/tests; bash ./test-prngs.sh"