name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.3 numpy

      - name: Build wheels
        run: |
          cd engine/src
          make grammars
          cd ../../
          cp -r engine/src engine/python/cmaboss/
          python -m cibuildwheel --output-dir wheelhouse engine/python

      - uses: actions/upload-artifact@v3
        with:
          path: engine/python/wheelhouse/*.whl